version: '3'
services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  crudapp:
    image: crudapp:1.0
    depends_on:
      - mongo_db
    ports:
      - 3000:3000
    environment:
      MONGO_URI : mongodb://mongo_db:27017
      USER :  admin
      PASS : admin
